# Generated by Django 5.2.6 on 2025-10-31 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_add_user_to_studentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='programs.participant'),
        ),
    ]
