# Generated by Django 5.2.4 on 2025-10-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_add_problemreport'),
        ('programs', '0006_alter_studentprofile_id'),
    ]

    operations = [
    ]
