# Generated by Django 5.2.4 on 2025-10-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_merge_20251031_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
