"""Django settings for the CA project.

This file was generated by 'django-admin startproject'.
The layout below organizes settings into clear sections for
easier maintenance and for preparing the project to be
deployed to production.

See Django docs:
  https://docs.djangoproject.com/en/5.2/topics/settings/
  https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path


# -----------------------------------------------------------------------------
# Base directory
# -----------------------------------------------------------------------------
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# -----------------------------------------------------------------------------
# Security
# -----------------------------------------------------------------------------
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@u$=afm!)-k2=vpmxu1h=1arxqc9fl7!%h5(kn^jr+g&j@wh#0'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG is True for development. Set to False in production.
DEBUG = True

# Hosts/domain names that are valid for this site
# During deployment update this to your domain names, e.g. ['example.com']
ALLOWED_HOSTS = []


# -----------------------------------------------------------------------------
# Applications
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]


# -----------------------------------------------------------------------------
# Middleware
# -----------------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# -----------------------------------------------------------------------------
# URL configuration
# -----------------------------------------------------------------------------
ROOT_URLCONF = 'CA.urls'


# -----------------------------------------------------------------------------
# Templates
# -----------------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# -----------------------------------------------------------------------------
# WSGI / ASGI application
# -----------------------------------------------------------------------------
WSGI_APPLICATION = 'CA.wsgi.application'


# -----------------------------------------------------------------------------
# Database
# -----------------------------------------------------------------------------
# Using SQLite for development. Replace with PostgreSQL/MySQL for production.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# -----------------------------------------------------------------------------
# Password validation
# -----------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# -----------------------------------------------------------------------------
# Internationalization
# -----------------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# -----------------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# -----------------------------------------------------------------------------
# URL prefix for static files
STATIC_URL = 'static/'

# Directory where `collectstatic` will collect static files for production
# STATIC_ROOT intentionally left to be configured per-deployment if needed.

# Additional directories to look for static files (placeholders)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Media files (user uploaded content)
# Configure these in production and ensure the webserver serves MEDIA_ROOT
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# -----------------------------------------------------------------------------
# Default primary key field type
# -----------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# -----------------------------------------------------------------------------
# Authentication / session
# -----------------------------------------------------------------------------
# After logout, redirect users to the login page. Update if you change login URL.
LOGOUT_REDIRECT_URL = '/accounts/login/'
# After login, send users to the homepage (index)
LOGIN_REDIRECT_URL = '/'

